# Generated by Django 6.0.7 on 2026-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_id", models.CharField(max_length=100, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("Google", "Google"),
                            ("Microsoft", "Microsoft"),
                            ("Apple", "Apple"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("record_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("missing_values_map", models.JSONField(blank=True, default=dict)),
                ("normalized_file_path", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ic_number", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("school", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=255)),
                ("cert_level", models.CharField(max_length=100)),
                ("cert_year", models.IntegerField()),
                ("multi_certified", models.BooleanField(default=False)),
                (
                    "eligibility_status",
                    models.CharField(default="pending", max_length=50),
                ),
            ],
            options={
                "ordering": ["state", "full_name"],
            },
        ),
    ]
