# Generated by Django 6.0.7 on 2026-07-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="certification",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
