# Generated by Django 6.0.7 on 2026-07-16 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_teacher_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(help_text='e.g. Microsoft Innovative Educator Expert (MIEE)', max_length=255)),
                ('required_keywords', models.JSONField(default=list, help_text='All keywords must appear in the combined programme+level text (lowercase). e.g. ["innovative educator", "expert"]')),
                ('exclude_keywords', models.JSONField(default=list, help_text='If any of these appear in the text, this rule does NOT match. e.g. ["trainer"]')),
                ('is_eligible', models.BooleanField(default=True, help_text='Count toward GPGD eligibility?')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = checked first within the same provider.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_rules', to='agents.provider')),
            ],
            options={
                'ordering': ['provider', '-priority', 'canonical_name'],
            },
        ),
    ]
