# Generated by Django 6.0.7 on 2026-07-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_provider_certificationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('ic_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('current_grade', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('tech_track', models.CharField(choices=[('Microsoft', 'Microsoft'), ('Google', 'Google'), ('Apple', 'Apple')], max_length=50)),
                ('certifications', models.TextField(help_text='List all certifications with issuing organisation and year.')),
                ('previous_gpgd', models.TextField(blank=True, help_text='Previous GPGD experience, if any.')),
                ('lnpt_current', models.DecimalField(decimal_places=2, help_text='Latest LNPT score.', max_digits=5)),
                ('lnpt_previous', models.DecimalField(decimal_places=2, help_text='Previous year LNPT score.', max_digits=5)),
                ('lnpt_two_years', models.DecimalField(decimal_places=2, help_text='Two years ago LNPT score.', max_digits=5)),
                ('training_experience', models.TextField(help_text='Training, coaching, mentoring, or sharing experience.')),
                ('awards', models.TextField(blank=True, help_text='Awards, recognitions, or achievements.')),
                ('additional_info', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Application Submitted', 'Application Submitted'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Application Submitted', max_length=50)),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='agents.teacher')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
