# Generated by Django 6.0.7 on 2026-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_deadline", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
