# Generated by Django 6.0.7 on 2026-07-16 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_programmesettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="compiled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="is_recommended",
            field=models.BooleanField(
                default=False,
                help_text="Auto-flagged to meet the district/state minimum quota for its technology track.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="moe_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="moe_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="moe_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="rank_in_state",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="state_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="state_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="state_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Application Submitted", "Application Submitted"),
                    ("Under Review", "Under Review"),
                    ("Compiled", "Compiled — Awaiting State Officer"),
                    ("State Approved", "State Approved — Awaiting MoE Officer"),
                    ("State Declined", "State Declined"),
                    ("Approved", "Approved — Recognised"),
                    ("Rejected", "Rejected (MoE)"),
                ],
                default="Application Submitted",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OfficerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("state_officer", "State Officer"),
                            ("moe_officer", "MoE Officer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Required for State Officers; leave blank for MoE Officer.",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officerprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
