# Generated by Django 6.0.7 on 2026-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_application_compiled_at_application_is_recommended_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("trigger_reason", models.CharField(max_length=255)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="The agent's own plain-language account of what it did.",
                    ),
                ),
                (
                    "actions_taken",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of {tool, input, result}.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
