# Generated by Django 6.0.7 on 2026-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_agentactivitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("email_auth", "Email — Authentication Failed"),
                            ("email_timeout", "Email — Connection Timed Out"),
                            ("email_connection", "Email — Could Not Connect"),
                            (
                                "email_invalid_recipient",
                                "Email — Invalid Recipient Address",
                            ),
                            ("email_other", "Email — Other Error"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        help_text="e.g. recipient name and email address.",
                        max_length=255,
                    ),
                ),
                (
                    "technical_detail",
                    models.TextField(
                        help_text="The raw exception message, for diagnosis."
                    ),
                ),
                (
                    "suggested_action",
                    models.TextField(
                        help_text="Plain-language guidance on what to check or fix."
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
