# Generated by Django 6.0.7 on 2026-07-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_errorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="award_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional award/recognition category, e.g. "Excellence in Digital Leadership".',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="recognized_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Calendar year this GPGD was officially recognised.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ActivityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_title", models.CharField(max_length=255)),
                ("training_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "target_audience",
                    models.JSONField(
                        default=list,
                        help_text="Subset of: teachers, students, school_leaders, others.",
                    ),
                ),
                ("num_participants", models.PositiveIntegerField()),
                (
                    "training_mode",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "venue_platform",
                    models.CharField(
                        help_text="Venue name, or online platform used.", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "photo_1",
                    models.ImageField(upload_to="activity_evidence/photos/%Y/%m/"),
                ),
                (
                    "photo_2",
                    models.ImageField(upload_to="activity_evidence/photos/%Y/%m/"),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="activity_evidence/documents/%Y/%m/",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gpgd",
                    models.ForeignKey(
                        limit_choices_to={"status": "Approved"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_reports",
                        to="agents.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-training_date", "-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text='"YYYY-MM" — the month this reminder was for.',
                        max_length=7,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reminders",
                        to="agents.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "unique_together": {("application", "period")},
            },
        ),
    ]
