# Generated by Django 6.0.7 on 2026-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_backfill_recognized_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmesettings',
            name='apply_form_field_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='apply_form_help_texts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='apply_form_section_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='invitation_email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='invitation_email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='recognition_letter_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='recognition_letter_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
