# Generated by Django 6.0.7 on 2026-10-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_invitationexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_by', models.CharField(blank=True, max_length=150)),
                ('attempted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
