# Generated by Django 6.0.7 on 2026-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_invitationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationrecord',
            name='status',
            field=models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=10),
        ),
    ]
