# Generated by Django 6.0.7 on 2026-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_invitationrecord_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='never_recognised',
            field=models.BooleanField(default=False, help_text='Declared on the form: has never held an annual national recognition.'),
        ),
        migrations.AddField(
            model_name='application',
            name='recognitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='reserved_place',
            field=models.BooleanField(default=False, help_text='Recommended through the place reserved for a teacher never recognised before.'),
        ),
    ]
