# Generated by Django 6.0.7 on 2026-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_track_limit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracklimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tracklimit',
            name='district',
            field=models.CharField(blank=True, default='', help_text='Blank = the whole state.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tracklimit',
            unique_together={('state', 'district', 'tech_track')},
        ),
    ]
