# Generated by Django 6.0.7 on 2026-10-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_track_limit_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Malaysian mobile number, stored as +60…', max_length=20),
        ),
    ]
