# Generated by Django 6.0.7 on 2026-10-05 22:31

from django.db import migrations, models


def split_participants(apps, schema_editor):
    """Reports from before the per-audience counts had one participant total. Put it under the first
    audience ticked (teachers, then students, school leaders, others), so the total stays right."""
    ActivityReport = apps.get_model('agents', 'ActivityReport')
    field_for = {'teachers': 'num_teachers', 'students': 'num_students',
                 'school_leaders': 'num_school_leaders', 'others': 'num_others'}
    for report in ActivityReport.objects.all():
        audience = [a for a in field_for if a in (report.target_audience or [])] or ['others']
        setattr(report, field_for[audience[0]], report.num_participants)
        report.save(update_fields=[field_for[audience[0]]])



class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_application_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='num_others',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='num_school_leaders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='num_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='num_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='school_leader_email',
            field=models.EmailField(blank=True, help_text="Receives the monthly report on this GPGD's activities.", max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='school_leader_name',
            field=models.CharField(blank=True, help_text='Principal / headmaster (Pengetua / Guru Besar).', max_length=255),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='monthly_reminder_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='monthly_reminder_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='reminder_day',
            field=models.PositiveSmallIntegerField(default=15, help_text='Day of the month the reminder goes out (15 = start of the 3rd week).'),
        ),
        migrations.AddField(
            model_name='programmesettings',
            name='report_day',
            field=models.PositiveSmallIntegerField(default=7, help_text="Day of the month last month's statistics go to directors and leaders (7 = end of the 1st week)."),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='num_participants',
            field=models.PositiveIntegerField(help_text='Total of the four counts below; set on save.'),
        ),
        migrations.CreateModel(
            name='MonthlyReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='"YYYY-MM": the month the report covers.', max_length=7)),
                ('level', models.CharField(max_length=15)),
                ('scope', models.CharField(blank=True, help_text='The state, district or school the report covers.', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('period', 'level', 'scope', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bstp', 'BSTP Director'), ('state', 'State Director'), ('district', 'District Education Lead')], max_length=10)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('level', 'state', 'district')},
            },
        ),
        migrations.RunPython(split_participants, migrations.RunPython.noop),
    ]
