# Generated by Django 6.0.7 on 2026-10-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_monthly_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recognition_letter_error',
            field=models.TextField(blank=True, help_text='Why the last attempt to email the letter failed.'),
        ),
        migrations.AddField(
            model_name='application',
            name='recognition_letter_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the Letter of Recognition was emailed.', null=True),
        ),
    ]
