# Generated by Django 6.0.7 on 2026-10-06 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_recognition_letter_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactivitylog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='success', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='"YYYY-MM": the month it covers.', max_length=7)),
                ('scope', models.CharField(help_text='"Malaysia" or a state.', max_length=100)),
                ('summary', models.TextField()),
                ('flags', models.JSONField(blank=True, default=list, help_text='Short "needs attention" points.')),
                ('status', models.CharField(choices=[('draft', 'Draft — awaiting Admin approval'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('edited', models.BooleanField(default=False, help_text='Changed by the Admin after the agent wrote it.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agentactivitylog')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('period', 'scope')},
            },
        ),
    ]
