"""
Django settings for mygpgd project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe) unless DJANGO_DEBUG=True is set, e.g. in your local .env.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        # Fallback so local dev works without extra setup. Never used when DEBUG=False.
        SECRET_KEY = "django-insecure-24gxih9&&0(5thq1sl@s*n_7%%zjb!$8rj60x5@7p$r=tmab@6"
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set via environment variable when DEBUG=False.'
        )

# Comma-separated list of allowed hostnames, e.g. "gpgd.moe.gov.my,www.gpgd.moe.gov.my".
# Defaults to localhost only, which is fine for local dev but must be overridden
# with the real domain(s) via DJANGO_ALLOWED_HOSTS before deploying.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

LOGIN_URL = '/agents/login/'
LOGIN_REDIRECT_URL = '/agents/officer/'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "agents",
]

MIDDLEWARE = [
    # First in, last out: wraps every other middleware so it captures the
    # full time a request takes, including static files. Purely observes
    # and logs — see agents/middleware.py for details.
    "agents.middleware.RequestLatencyLoggingMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "agents.middleware.StateOfficerRestrictMiddleware",
    "agents.middleware.MoeOfficerRestrictMiddleware",
]

ROOT_URLCONF = "mygpgd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mygpgd.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Defaults to local SQLite. Set DB_HOST (e.g. in .env) to switch to the
# centralized PostgreSQL database instead — DB_SCHEMA is put first in the
# connection's search_path so tables land in that schema rather than "public".
if os.environ.get('DB_HOST'):
    DB_SCHEMA = os.environ.get('DB_SCHEMA', 'public')
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get('DB_NAME', ''),
            "USER": os.environ.get('DB_USER', ''),
            "PASSWORD": os.environ.get('DB_PASSWORD', ''),
            "HOST": os.environ.get('DB_HOST', ''),
            "PORT": os.environ.get('DB_PORT', '5432'),
            "OPTIONS": {
                "options": f"-c search_path={DB_SCHEMA},public",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            # Overridable so the db file can live on a mounted volume in Docker
            # (see docker-compose.yml) instead of the container's writable layer.
            "NAME": os.environ.get('DJANGO_DB_PATH', str(BASE_DIR / "db.sqlite3")),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` gathers files for production; whitenoise serves them from here.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Teacher-submitted evidence (activity report photos/documents) — real Django-managed
# storage, unlike the ad-hoc temp_uploads/ convention used for admin-side Excel uploads.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------------------------------
# HTTPS / transport security
#
# Applied whenever DEBUG=False, i.e. in production. Assumes the deployment is
# served over HTTPS end-to-end. If you put this behind a reverse proxy/load
# balancer that terminates TLS, also set SECURE_PROXY_SSL_HEADER accordingly.
# ---------------------------------------------------------------------------
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if not DEBUG else None
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.ERROR: "danger",
}

# ---------------------------------------------------------------------------
# Email configuration
#
# Real emails are only delivered when EMAIL_HOST_USER is set (via environment
# variables). Until then, the app falls back to the console backend, which
# safely prints each email to the server terminal instead of sending it.
#
# To send real invitations from jayanthi@moe.gov.my, set these environment
# variables (do NOT hard-code the password in this file):
#
#   PowerShell (current session only):
#     $env:GPGD_EMAIL_HOST      = "smtp.gmail.com"        # ask IT for the moe.gov.my SMTP host
#     $env:GPGD_EMAIL_PORT      = "587"
#     $env:GPGD_EMAIL_USER      = "jayanthi@moe.gov.my"
#     $env:GPGD_EMAIL_PASSWORD  = "your-app-password"     # an app password, not your login password
#     $env:GPGD_EMAIL_USE_TLS   = "true"
#
#   To persist across reboots, use: setx GPGD_EMAIL_USER "jayanthi@moe.gov.my"  (etc.)
#
# Common SMTP hosts:
#   Google Workspace / Gmail : smtp.gmail.com          port 587 (TLS)
#   Microsoft 365 / Outlook  : smtp.office365.com      port 587 (TLS)
#   Official MOE server      : (obtain host/port from your IT department)
# ---------------------------------------------------------------------------
import os

EMAIL_HOST = os.environ.get('GPGD_EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('GPGD_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('GPGD_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('GPGD_EMAIL_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('GPGD_EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('GPGD_EMAIL_USE_SSL', 'false').lower() == 'true'
# Without this, a blocked/unreachable SMTP server makes send_mail() hang indefinitely
# instead of raising — which would hang the whole "Send Invitations" request.
EMAIL_TIMEOUT = int(os.environ.get('GPGD_EMAIL_TIMEOUT', '20'))

if EMAIL_HOST_USER and EMAIL_HOST:
    # Credentials provided → send real emails over SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get(
        'GPGD_EMAIL_FROM', f'GPGD Programme <{EMAIL_HOST_USER}>'
    )
else:
    # No credentials → print emails to the console (safe development default)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'GPGD Programme <noreply@moe.gov.my>'

# Base URL used to build the secure application links inside invitation emails.
# Set GPGD_SITE_URL to your public/staging domain in production.
GPGD_SITE_URL = os.environ.get('GPGD_SITE_URL', 'http://localhost:8000')

# ---------------------------------------------------------------------------
# Request latency logging
#
# agents.middleware.RequestLatencyLoggingMiddleware times every request and
# writes the result here. Check logs/latency.log and search for "SLOW " to
# see which pages are taking too long — this is what tells you whether the
# app is actually usable for users on weak/rural internet connections.
# Doesn't change how any request is handled, only records how long it took.
# ---------------------------------------------------------------------------
os.makedirs(BASE_DIR / "logs", exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "latency": {
            "format": "%(asctime)s %(levelname)s %(message)s",
        },
    },
    "handlers": {
        "latency_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(BASE_DIR / "logs" / "latency.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB per file
            "backupCount": 3,
            "formatter": "latency",
        },
        "latency_console": {
            "class": "logging.StreamHandler",
            "formatter": "latency",
        },
    },
    "loggers": {
        "agents.latency": {
            "handlers": ["latency_file", "latency_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ---------------------------------------------------------------------------
# Pipeline agent (Anthropic Claude) — drives the certification-to-compilation
# pipeline autonomously between the upload step and State Officer review.
# Get a key at https://console.anthropic.com/ and set ANTHROPIC_API_KEY in .env
# ---------------------------------------------------------------------------
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
